owner: tensoract # Organization 
repo: status

sites:
  - name: Google
    url: https://www.google.com
  - name: Student UIT
    url: https://student.uit.edu.vn/

status-website:
    baseUrl: /status
    name: Server Status
    faviconSvg: https://tensoract.github.io/assets/logo-nobackground.svg
    logoUrl: https://raw.githubusercontent.com/tensoract/status/master/assets/logo-nobackground.svg
    introTitle: "Server Status"
    introMessage: This is the website used for displaying realtime status of our server.
    theme: night
   
    
    
    
